pcm-memory:mainloop: Always flush cout
intel/pcm pull request #374
Opened 2022-02-28 20:51 UTC by bsdimp

Flushing cout in cvs mode is also useful when the output is a pipeline
using the values to display in real time. As such, always flush the cout
buffers at the start of the main loop.

Signed-off-by: Warner Losh <imp@FreeBSD.org>

2022-02-28 21:25 UTC, ogbrugge approved these changes
Looks good to me

2022-03-05 15:03 UTC, opcm commented
thanks for the patch, this is useful. But to reduce the overhead for non-interactive mode when sampling with a higher frequency the flushing should be avoided in csv mode. The flushing should be optional like in pcm-iio: https://github.com/opcm/pcm/blob/58039287e0ee63edcaa60bdbf837d536e4e417da/src/pcm-raw.cpp#L74 Could you please implement it similarly?

2022-03-05 15:05 UTC, opcm requested changes
please make the flushing optional

2022-10-19 14:43 UTC, rdementi commented
> please make the flushing optional

has been implemented in the latest release

2022-10-19 14:43 UTC, closed without merging