minor fixes to grafana scripts
intel/pcm pull request #611
Opened 2023-11-24 11:28 UTC by vimalk78

Updated scripts to
  - use network instead of link
  - use podman or docker

2023-11-24 13:56 UTC, opcm requested changes
thanks for the change. Would you mind to make it run on docker-only based systems too as default? using podman should be an additional option. There are also README files in PCM which refer to docker (git grep docker)

2023-11-25 07:09 UTC, vimalk78 commented
> thanks for the change. Would you mind to make it run on docker-only based systems too as default? using podman should be an additional option. There are also README files in PCM which refer to docker (git grep docker)

@opcm updated as per your suggestion.

2023-11-26 16:16 UTC, opcm requested changes

2023-11-26 16:16 UTC, opcm commented on scripts/grafana/start.sh
> +${CTR_RUN} run -d --name telegraf --network=influxdb -v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro telegraf
it should be influxdb-network

2023-11-26 16:16 UTC, opcm commented on scripts/grafana/start.sh
> +${CTR_RUN} run -d --network=influxdb --name grafana -p 3000:3000 -v $PWD/provisioning:/etc/grafana/provisioning -v $PWD/grafana_volume:/var/lib/grafana grafana/grafana
same here

2024-01-04 17:26 UTC, vimalk78 commented on scripts/grafana/start.sh
> +${CTR_RUN} run -d --name telegraf --network=influxdb -v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro telegraf
updated

2024-01-04 17:26 UTC, vimalk78 commented on scripts/grafana/start.sh
> +${CTR_RUN} run -d --network=influxdb --name grafana -p 3000:3000 -v $PWD/provisioning:/etc/grafana/provisioning -v $PWD/grafana_volume:/var/lib/grafana grafana/grafana
updated

2024-02-02 17:24 UTC, vimalk78 commented
Hello @opcm , can we get this merged?

2024-02-02 17:46 UTC, opcm approved these changes
LGTM. Sorry I thought this was merged already. Thanks for the reminder

2024-02-02 17:47 UTC, merged